### ISSUE TITLE
Progress bar / Timer

### ISSUE THREAD

**Issue by alexandre-laine** [Cypriendtr/Brainhack_Marseille_2024_Hands_on_python_tutorial#4]

**Comment by alexandre-laine** [comment]
import time
add to requirement
use sleep

**Comment by alexandre-laine** [comment]
in RISE

**Comment by Cypriendtr** [comment]
import time
import tqdm

def func_timer(duration:float): 
    """
    Parameters
    ---------
    duration : Duration in minutes
    Returns
    ---------
    Progress bar of the duration referenced
    """
    dur_sec = duration * 60
    for i in tqdm.trange(dur_sec):
        time.sleep(1)

func_timer(duration = 1)

**Comment by alexandre-laine** [comment]
~~~python
def func_timer(duration:float):
    """
    Parameters
    ---------
    duration : Duration in minutes
    Returns
    ---------
    Progress bar of the duration referenced
    """

    dur_sec = duration * 60
    for i in tqdm.trange(dur_sec, ncols=90, desc="Exercise timer", ascii="_|"):
        time.sleep(1)
~~~
